### ISSUE TITLE
Using model other than User

### ISSUE THREAD

**Issue by dannydinges** [themsaid/nova-cashier-manager#14]
If Cashier is setup on a model other than User can this package be used. I have Billable setup on a "Client" model and it looks like the package still tries to reference /user when getting the subscription.

**Comment by themsaid** [comment]
We use the model you set in the cashier configuration: https://github.com/themsaid/nova-cashier-manager/blob/master/src/CashierToolController.php#L41

**Comment by DanielSteadfast** [comment]
@dannydinges It looks like the API routes just have user hardcoded, but it does use the stripe model you have defined.

**Comment by dannydinges** [comment]
@themsaid But the API routes are hard coded as @DanielSteadfast has pointed out so non of the subscriptions show up for the model you set in cashier.

**Comment by themsaid** [comment]
@dannydinges the API routes are just named as user but it's indeed using the model you set for cashier.

**Comment by dannydinges** [comment]
@themsaid Got it figured out. Was a little confused on how it works. Thanks for the help!

**Comment by joshpennington** [comment]
@dannydinges Can you tell me what you did to resolve the problem? 

I am using a different model than User and I think I am having a similar problem. I think I have everything configured properly so I am hoping we maybe missed the same thing.

**Comment by themsaid** [comment]
@joshpennington do you have the config value `services.stripe.model` set correctly? What errors do you get if so?

**Comment by joshpennington** [comment]
I do have the config value set to the model that I have Cashier setup on. I do not get any errors to speak up (at least not in any of the places I know to look). 

I currently am getting a message that says "User has no subscription".

**Comment by Rias500** [comment]
Are you using a different subscription name? For example `main` instead of `default`? Then you need to change this in the `nova-cashier-manager.php` config file.

**Comment by joshpennington** [comment]
That was the problem. I had named my product something different. Changing that to match made it start to work.

Thank you!

**Comment by hackel** [comment]
Cashier itself uses "user" to refer to whichever model the subscription is attached to, so I think it's appropriate to remain consistent here.  Working fine for me using a different model.

@dannydinges This issue can be closed.
