### ISSUE TITLE
Getting "App\Nova\CashierResourceTool not found"

### ISSUE THREAD

**Issue by matteocuturello** [themsaid/nova-cashier-manager#20]
After installing the package following your procedure, I get this error: "App\Nova\CashierResourceTool not found" in my User's Resource

**Comment by thomasjohnkane** [comment]
Me too. Still looking into this.

**Comment by thomasjohnkane** [comment]
Just import it at the top, or do this:

"\Themsaid\CashierTool\CashierResourceTool::make()->onlyOnDetail()" to make sure your namespace is correct.
