### ISSUE TITLE
Disable Card on Entities without Subscription

### ISSUE THREAD

**Issue by hanspagel** [themsaid/nova-cashier-manager#3]
Hey @themsaid! Thanks for creating Cashier Manager. :) It's the first package I set up on Nova.

Just one little thing: Is it possible to hide the Card on Entities without Subscription?

![pqcqjdv0bc-1](https://user-images.githubusercontent.com/1577992/44469945-d6f3ba80-a628-11e8-8d5b-44baab0c1d97.png)

**Comment by themsaid** [comment]
You mean they don't have an active subscription? Or the entity itself isn't billable?

**Comment by themsaid** [comment]
can someone please explain the issue? :) See any errors in the console? Is the model billable? see any errors in the logs?

**Comment by TheDeepNate** [comment]
@themsaid There's not dist files so nothing is loading, you had the .gitignore to ignore them files... Can you  compile them and send a PR?

**Comment by themsaid** [comment]
ah, did that and released. Thanks

**Comment by hanspagel** [comment]
I thought it's empty for teams without a subscription, but it's empty for all entities here. 

I don't see an Exception or anything. I'm using Uuids, maybe this is the reason why? I'll try to look into it later.

**Comment by egyptik** [comment]
I found the issue, you forgot one step in the install instructions! People should also update the `tools` array in the `NovaServiceProvider`:

```php
    /**
     * Get the tools that should be listed in the Nova sidebar.
     *
     * @return array
     */
    public function tools()
    {
        return [
            new CashierTool(),
        ];
    }`

**Comment by egyptik** [comment]
Just opened a PR: #7

**Comment by tobz-nz** [comment]
Note that the docs are updated in github but not on novapackages.com where many people will be reading them. fyi.
